### ISSUE TITLE
Institution Room 엔터티 변경 및 Institution_Address 엔터티 신규 생성

### ISSUE THREAD

**Issue by HyunWooParkKEIG** [nsnnsn12/pr2s#109]
#### Description
테이블 구조 변경에 따라 Institution_Address 테이블 신규 생성 및 Institution, Room 엔터티 변경 필요

#### Tasks
- [x] Institution 엔터티 변경
- [x] Room 엔터티 변경
- [x] Institution_Address 엔터티 신규 생성
