### ISSUE TITLE
대여를 위한 방 조회 기능 구현

### ISSUE THREAD

**Issue by nsnnsn12** [nsnnsn12/pr2s#113]
#### Description
대여를 위해 등록되어 있는 방 조회

#### Tasks
- [ ] 사용인원을 이용한 검색조건
- [ ] 예약 가능 시간(선택한 날짜의 대한 운영여부) 검색조건
- [ ] 태그 검색 조건
- [ ] 지역 검색조건
- [ ] 사용용도 검색조건
- [ ] 제목 검색조건
- [ ] 지도 검색
- [ ] 테스트 케이스 작성
- [ ] xy 좌표 데이터 베이스의 position 타입 사용
