### ISSUE TITLE
[TODO] 엔티티 매핑 작업(나현)

### ISSUE THREAD

**Issue by nahyunoh** [nsnnsn12/pr2s#17]
#### Relation Closed Issue
#11

#### TODO
- [x] File 객체 필요
- [x] workDay Enum Type 정의 필요
- [x] startTime endTime 기간 임베디드 타입 정의 필요
- [x] 답글 자체조인 가능 여부 확인

#### TODO Issue Numbers
- #10
- #20 
- #23
