### ISSUE TITLE
ClientMemberService join 파일 기능 추가

### ISSUE THREAD

**Issue by nsnnsn12** [nsnnsn12/pr2s#51]
#### Description
join 메소드의 file id를 입력받아 member entity에 File entity 세팅

#### Tasks
- [x] file id 파라미터 추가
- [x] 해당 기능 테스트 구현
- [x] file이 없을 경우 예외처리
