### ISSUE TITLE
ClientMemberService 삭제 여부 확인 추가 

### ISSUE THREAD

**Issue by nsnnsn12** [nsnnsn12/pr2s#63]
#### Description
ClientMemberService 내 삭제 여부 확인 로직 추가

#### Tasks
- [x] 회원 조회 시 논리적으로 삭제된 사용자에 대한 예외 처리 추가
- [x] 기관 조회 시 논리적으로 삭제된 기관에 대한 예외 처리 추가
- [x] 회원 조회를 사용하는 기능에 대한 예외 테스트 추가
- [x] 기관 조회를 사용하는 기능에 대한 예외 테스트 추가
